#:schema node_modules/wrangler/config-schema.json
name = "invitationlegacy"
main = "index.js"
compatibility_date = "2024-04-03"

[assets]
directory = "."

[[kv_namespaces]]
binding = "INVITATION_DB"
id = "7bbb1d6a1d2b42aa8bdb72b1e174f205"
